version: '3.1'
services:
  wordpress:
    image: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: wp_db_user    ## Hier Benutzer eingeben ##
      WORDPRESS_DB_PASSWORD: PASSWORD ## Hier Passwort eingeben ##
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /path/to/data:/var/www/html ## Hier Pfad eingeben ##
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress-1.entrypoints=http"
      - "traefik.http.routers.wordpress-1.rule=Host(`domain.tld`)"  ## Hier eure Domain eingeben ##
      - "traefik.http.middlewares.wordpress-1-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.wordpress-1.middlewares=wordpress-1-https-redirect"
      - "traefik.http.routers.wordpress-1-secure.entrypoints=https"
      - "traefik.http.routers.wordpress-1-secure.rule=Host(`domain.tld`)" ## Hier eure Domain eingeben ##
      - "traefik.http.routers.wordpress-1-secure.tls=true"
      - "traefik.http.routers.wordpress-1-secure.tls.certresolver=http"
      - "traefik.http.routers.wordpress-1-secure.service=wordpress-1"
      - "traefik.http.services.wordpress-1.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - default
  wordpress-db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_db_user     ## Hier selben Benutzer eingeben ##
      MYSQL_PASSWORD: PASSWORD ## Hier selbes Passwort eingeben ##
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /opt/docker/blog/database:/var/lib/mysql
    networks:
      - default
networks:
  proxy:
    external: true
